// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use the direct (non-pooled) connection here so `prisma migrate` works reliably.
    // See .env.example for why DATABASE_URL and DIRECT_URL are both defined.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
